name: LowlandTech.Testing.Features Build, Pack, and Publish

on:
  push:
    branches:
      - main
      - release/*
      - hotfix/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code with full history to avoid shallow clone issues
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the entire git history

      # Setup .NET 9.0
      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # Restore .NET dependencies
      - name: Restore dependencies
        run: dotnet restore src/lowlandtech.generator.application 

      # Build the .NET project
      - name: Build project
        run: dotnet build src/lowlandtech.generator.application  --no-restore --configuration Release

      # Pack the project Plugin into a NuGet package
      - name: Pack the project Plugin
        run: dotnet pack src/lowlandtech.generator /p:PackageVersion=2025.7.1 --no-build --configuration Release -o ./nuget

      # Pack the project Domain into a NuGet package
      - name: Pack the project Domain
        run: dotnet pack src/lowlandtech.generator.domain /p:PackageVersion=2025.7.1 --no-build --configuration Release -o ./nuget

      # Pack the project Infrastructure into a NuGet package
      - name: Pack the project Infrastructure
        run: dotnet pack src/lowlandtech.generator.infrastructure /p:PackageVersion=2025.7.1 --no-build --configuration Release -o ./nuget

      # Pack the project Application into a NuGet package
      - name: Pack the project Application
        run: dotnet pack src/lowlandtech.generator.application /p:PackageVersion=2025.7.1 --no-build --configuration Release -o ./nuget

      # Publish the NuGet package (only on the main branch)
      - name: Publish NuGet package
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push ./nuget/*.nupkg --source https://nuget.pkg.github.com/lowlandtech/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
